const allProjectsList = [
"Isle of Tree",
"North Park",
"Abhee Celestial City",
"Abhee Riviera Royale",
"Adarsh Parkland",
"Adarsh Welkin Park",
"Aiikya Village",
"ars signaturehomes",
"Arvind Orchards",
"Aryan Krishnaa Divine",
"Assetz 66 and Shibui",
"Assetz Inspira Melodies of Life",
"Assetz Promise of Spring",
"Assetz Sora and Saki",
"Assetz Sun & Sanctum",
"Aston Park @ The Prestige City",
"Aura",
"Aurum At Brigade El Dorado",
"Azalea",
"Azur",
"Beverly Hills",
"Bhoo Aabharana",
"Binary Temple Tree",
"Birla Ojasvi",
"Birla Trimaya",
"Brigade Calista",
"Brigade Insignia",
"Brigade Oasis",
"Brigade Sanctuary",
"Brilio Brigade Valencia",
"C R Serenity",
"Casagrand Amor",
"Casagrand Flamingo",
"Cascedia TVS Emerald",
"Century Liva",
"Century Novus",
"Century Trails",
"Classic Bulwark Village",
"Coco Aldea Rivatani",
"CoEvolve Florenza",
"Concorde Mayfair",
"Concorde Neo",
"Dioro at Brigade Eldorado",
"DNR Arista",
"DNR Parklink",
"DNR Solace",
"DS Max Sky Samurai",
"DS Max Sky Sanjeevini",
"Earth Aroma",
"Earthsong",
"East Park Residency",
"Elegant Hermitage",
"Elegant Tranquility",
"Embassy East Avenue",
"Engrace Vista",
"Equinox Sunrise",
"Fairmont at Brigade Orchards",
"Falcon",
"Folium By Sumadhura",
"Garuda Grand",
"Gina Artize",
"Godrej Athena",
"Godrej Lakeside Orchard",
"Godrej Splendour",
"Godrej Yashvantpur",
"GRC Saffron Skies",
"Green Orchid",
"Guru Punvaanii Eka",
"Guru Punvaanii Etasha",
"Icon Calista",
"Inspira Infinity",
"Isle of Tree",
"Ivory at Brigade Orchards",
"JRC Wild Woods",
"Kns Ananta",
"KNS Athena",
"KNS Billore",
"KNS Candrill",
"Krishna Lakefront",
"Lagos",
"Lakeside24",
"Living Tree Kalyani",
"Maanya Tulip",
"Mahendra Arto Helix",
"Mahindra Zen",
"Mana Dale",
"Mana Earthy Abode",
"Mana Verdant",
"Merusri Sunlit Grove Annexe",
"Mirabelle",
"Mitra Eternia",
"Nature Nxt",
"Nexsa Acuity",
"Nikoo Homes VI",
"Novo Gardenia",
"Oceanus White Meadows",
"Orchid Bloomsberry",
"Orchid Life",
"Orchid Platinum",
"Orchids Salisbury",
"Parkwest",
"Pioneer KRS Park Royal",
"Prestige Glenbrook",
"Prestige Lavender Fields",
"Prestige Park Grove",
"Prestige Pine Forest",
"Prestige Raintree Park",
"Prestige Serenity Shores",
"Prestige Somerville",
"Prestige Southern Star",
"Pride Altius",
"Provident Botanico",
"Provident Ecopolitan",
"Provident Equinox",
"PSR Vanasree",
"Purva Aero City",
"Purva Kensho Hills",
"Purvankara Bellandur",
"Ragam Melodies",
"Raheja Vivarea",
"Ramsons Trendsquare East Park",
"Rohan Ekanta",
"Sai Amogha",
"Sanjeevini Aarna",
"Sarang By Sumadhura",
"Sattva Bliss",
"Sattva Lumina",
"Sattva Song Bird",
"Sattva Springs",
"Shell Sapphire",
"Shriram Esquire",
"Shriram Sapphire",
"Shriram Serenity",
"Shriram Smash Hit",
"Signature Pristine",
"Signature Tulips Uptown",
"Sizzle Sidvin Horizon",
"SLV Millenial",
"SNN Estates Felicity",
"Sobha Ayana at Dream Acres Wing 60 to 71",
"Sobha Infinia",
"Sobha Neopolis",
"Spectra Parijatha",
"Srivari Forest Breeze",
"SSVR Niyaara",
"Sumadhuhra Capitol",
"Sumadhura Epitome",
"SVB Maplewoods",
"Tangled Up In Green",
"TATA Carnatic",
"Tata Raagam",
"Tetra Grand Green Essence",
"The Earth",
"The Grand Strand Address",
"The Imperial Address",
"The Right Life",
"Trifecta Retto",
"Trifecta Vanto",
"Vaishno Ambaram",
"Vajram Newtown",
"Vanantara Jiva",
"Vatavaran Realty",
]

export default allProjectsList;