export const AREA_DATA = [
    {
      Area: "Central Bangalore",
      MicroMarkets: [
        "Lal Bagh Road",
        "M G Road",
        "HSR Layout",
        "Koramangala",
        "Indiranagar",
        "Rajaji Nagar",
        "Kempapura Agrahara",
        "J P Nagar",
        "Banaswadi",
        "Nandi Hills Road",
      ],
    },
    {
      Area: "East Bangalore",
      MicroMarkets: [
        "Choodasandra",
        "Marathahalli",
        "Gopasandra",
        "Sarjapur",
        "Kadugodi",
        "Hosa Road",
        "Itangur",
        "Huskur",
        "Varthur",
        "Panathur",
        "Whitefield",
        "Brookefield",
        "Kundalahalli",
        "K R Puram",
        "Sarjapur Road",
        "Yamare",
        "Sompura",
        "Uttarahalli",
        "Velapura Colony",
        "Hoskote",
        "Gunjur",
        "Malur",
        "Doddabanahalli",
        "Jigala",
        "Gattahalli",
        "Tyayakana Halli",
        "Kannamangala",
        "Kodathi",
        "Dommasandra",
        "Channasandra",
        "Chikka Tirupati",
        "Muthsandra",
        "Bellandur",
        "Kaggalipura",
        "Attibele",
        "Budigere Road",
        "Carmelaram",
        "Anekal",
      ],
    },
    {
      Area: "North Bangalore",
      MicroMarkets: [
        "Rajanukunte",
        "Sathanur",
        "Devanahalli",
        "Tumkur Road",
        "Yelahanka ISRO Layout",
        "Kithiganur",
        "Rmv Extension",
        "Bellahalli",
        "Thirumenahalli",
        "HBR Layout",
        "New Int Airport Road",
        "Yelahanka",
        "Geddalahalli",
        "Hennur Main Rd",
        "Yelahanka New Town",
        "Budigere Cross",
        "Jalahalli",
        "Jakkur Road",
        "Bagaluru",
        "Hosahalli",
        "Yelahanka airforce",
        "Kogilu",
        "K R Puram",
        "Hebbal",
        "Nandi Hills",
        "Nelamangala",
        "Thanisandra Rd",
        "Doddaballapura",
        "Yeshwanthpur",
        "Hanumanthappa Layout",
        "Byatarayanapura",
        "Kodigehalli",
        "RMV 2nd Stage",
        "Shettigere",
        "Navarathna Agrahara",
        "Thanisandra",
        "Hoskote",
        "Huskur",
        "Horamavu",
      ],
    },
    {
      Area: "South Bangalore",
      MicroMarkets: [
        "Anekal",
        "Chandapura",
        "Attibele",
        "Bannerghatta Road",
        "Kaggalipura",
        "Begur Road",
        "Banashankari",
        "Bommasandra",
        "Vajarahalli",
        "Hulimavu",
        "Electronic City",
        "Rajarajeshwari Nagar",
        "Kothnur",
        "Kanakapura Road",
        "Akshayanagara",
        "Gottigere",
        "Begur",
        "Padmanabhanagar",
        "Judicial Layout",
        "Kengeri",
        "Hosa Road",
        "Electronic City Phase 2",
        "Bannerghatta",
        "Jigani",
      ],
    },
    {
      Area: "West Bangalore",
      MicroMarkets: [
        "Kengeri",
        "Mysore Road",
        "Thavarekere",
        "Bidadi",
        "Vijaynagar",
        "Nagasandra",
      ],
    },
  ];