export const TASK_TYPE_OPTIONS = [
  { value: 'collect-requirement', label: 'Collect Requirement' },
  { value: 'collect-eoi', label: 'Collect EOI' },
  { value: 'loan-discussion', label: 'Loan Discussion' },
  { value: 'plan-site-visit', label: 'Plan Site Visit' },
  { value: 'tds-payment', label: 'TDS Payment' },
  { value: 'lead-registration', label: 'Lead Registration' },
  { value: 'other-discussion', label: 'Other Discussion' },
  { value: 'collect-emd', label: 'Collect EMD' },
  { value: 'help-in-bidding', label: 'Help In Bidding' },
  { value: 'customer-kyc', label: 'Customer KYC' },
  { value: 'create-site-credential', label: 'Create Site Credential' },
  { value: 'emd-amount-return', label: 'EMD Amount Return' },
  { value: 'confirm-25-payment', label: 'Confirm 25% Payment' },
  { value: 'raise-invoice', label: 'Raise Invoice' },
  { value: 'unit-booking', label: 'Unit Booking' },
  { value: 'rent-collection', label: 'Rent Collection' },
  { value: 'find-tenant', label: 'Find Tenant' },
  { value: 'electricity-bill', label: 'Electricity Bill' },
  { value: 'title-clearance', label: 'Title Clearance' },
  { value: 'sell-property', label: 'Sell Property' },
  { value: 'khata-transfer', label: 'Khata Transfer' },
  { value: 'auction-day', label: 'Auction Day' },
  { value: 'bank-forms', label: 'Bank Forms' },
  { value: 'submit-emd-to-bank', label: 'Submit EMD To Bank' },
  { value: 'price-update', label: 'Price Update' },
  { value: 'submit-eois', label: 'Submit EOIs' },
  { value: 'share-property', label: 'Share Property' },
]